#!/usr/bin/env bash
set -e

STAGING_DIR="/tmp/staged/app"

INSTALLATION_DIR=$1

ln -sf $INSTALLATION_DIR /app/httpd

function build_apr() {
  curl -f -L -O "http://apache.mirrors.tds.net/apr/apr-$APR_VERSION.tar.gz"
  tar zxf "apr-$APR_VERSION.tar.gz"
  pushd "apr-$APR_VERSION"
  ./configure --prefix="$STAGING_DIR/libapr-$APR_VERSION"
  make -j 3
  make install
  popd
}

function build_apr_iconv() {
  curl -f -L -O "http://apache.mirrors.tds.net/apr/apr-iconv-$APR_ICONV_VERSION.tar.gz"
  tar zxf "apr-iconv-$APR_ICONV_VERSION.tar.gz"
  pushd "apr-iconv-$APR_ICONV_VERSION"
  ./configure \
    --prefix="$STAGING_DIR/libapr-iconv-$APR_ICONV_VERSION" \
    --with-apr="$STAGING_DIR/libapr-$APR_VERSION/bin/apr-1-config"
  make -j 3
  make install
  popd
}

function build_apr_util() {
  curl -f -L -O "http://apache.mirrors.tds.net/apr/apr-util-$APR_UTIL_VERSION.tar.gz"
  tar zxf "apr-util-$APR_UTIL_VERSION.tar.gz"
  pushd "apr-util-$APR_UTIL_VERSION"
  ./configure \
    --prefix="$STAGING_DIR/libapr-util-$APR_UTIL_VERSION" \
    --with-iconv="$STAGING_DIR/libapr-iconv-$ICONV_VERSION" \
    --with-crypto \
    --with-openssl \
    --with-mysql \
    --with-pgsql \
    --with-gdbm \
    --with-ldap \
    --with-apr="$STAGING_DIR/libapr-$APR_VERSION"
  make -j 3
  make install
  popd
}

function build_required_libs() {
  build_apr
  build_apr_iconv
  build_apr_util
}

function build_httpd_24() {
  curl -f -L -O "http://apache.osuosl.org/httpd/httpd-$HTTPD_VERSION.tar.bz2"
  tar jxf "httpd-$HTTPD_VERSION.tar.bz2"
  pushd "httpd-$HTTPD_VERSION"
  ./configure \
    --prefix="/app/httpd" \
    --with-apr="$STAGING_DIR/libapr-$APR_VERSION" \
    --with-apr-util="$STAGING_DIR/libapr-util-$APR_UTIL_VERSION" \
    --enable-mpms-shared="worker event" \
    --enable-mods-shared=reallyall \
    --disable-isapi \
    --disable-dav \
    --disable-dialup
  make -j 3
  make install
  popd
}

# build required libs & httpd
build_required_libs
build_httpd_24

# Remove unnecessary files and config
cd "/app/httpd"
rm -rf build/ cgi-bin/ error/ icons/ include/ man/ manual/ htdocs/
rm -rf conf/extra/* conf/httpd.conf conf/httpd.conf.bak conf/magic conf/original

# Install required libraries
mkdir "/app/httpd/lib"
cp "$STAGING_DIR/libapr-$APR_VERSION/lib/libapr-1.so.0" "/app/httpd/lib"
cp "$STAGING_DIR/libapr-util-$APR_UTIL_VERSION/lib/libaprutil-1.so.0" "/app/httpd/lib"
cp "$STAGING_DIR/libapr-iconv-$APR_ICONV_VERSION/lib/libapriconv-1.so.0" "/app/httpd/lib"

echo "Done!"
