#!/usr/bin/env bash
set -e

INSTALLATION_DIR=$1

apt-get update
apt-get -y install maven openjdk-7-jdk

git clone --depth 1 --branch GIT_TAG https://github.com/jruby/jruby.git
cd jruby
mvn -Djruby.default.ruby.version=RUBY_VERSION

cp -r bin/ $INSTALLATION_DIR
cp -r lib/ $INSTALLATION_DIR
