#!/usr/bin/env bash
set -e

INSTALLATION_DIR=$1
PREFIX='/app/.heroku/vendor'

mkdir -p /app/.heroku
ln -s $INSTALLATION_DIR $PREFIX

curl https://www.python.org/ftp/python/BINARY_VERSION/Python-BINARY_VERSION.tgz | tar xzf -
cd Python-BINARY_VERSION
./configure --prefix=${PREFIX} --enable-shared --with-ensurepip=no
make
make install

# For python3 only:
cd $INSTALLATION_DIR/bin
if ! [ -f ./python ]; then
  ln -s ./python3 ./python
fi
