#!/usr/bin/env bash
set -e

INSTALL_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PREFIX='/app/.heroku/vendor'

mkdir -p /app/.heroku
ln -s $INSTALL_DIRECTORY $PREFIX

curl https://www.python.org/ftp/python/BINARY_VERSION/Python-BINARY_VERSION.tgz | tar xzf -
cd Python-BINARY_VERSION
./configure --prefix=${PREFIX} --enable-shared --with-ensurepip=no
make
make install

# For python3 only:
cd $INSTALL_DIRECTORY/bin
if ! [ -f ./python ]; then
  ln -s ./python3 ./python
fi
