#!/usr/bin/env bash
set -e

INSTALLATION_DIR=$1
PREFIX='/app/vendor/RUBY_DIRECTORY'

mkdir -p /app/vendor
ln -s $INSTALLATION_DIR $PREFIX

git clone --depth 1 --branch GIT_TAG https://github.com/ruby/ruby.git
cd ruby
apt-get install -y autoconf
autoconf
./configure --prefix=${PREFIX} --enable-load-relative --disable-install-doc
make install
